openapi: 3.0.3
info:
  title: Product Catalog API
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /products:
    post:
      summary: Create product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreate'
      responses:
        '201':
          description: Created
    get:
      summary: List products
      responses:
        '200':
          description: OK
  /products/{id}:
    get:
      summary: Get product by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        sku:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        stock:
          type: integer
    ProductCreate:
      type: object
      required: [sku,name,price]
      properties:
        sku:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        stock:
          type: integer
