apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP     # Internal cluster-only access (recommended for DB).
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
